author: æ­åŸå°åˆ˜ # ä½œè€…
description: æ­åŸå°åˆ˜çš„ä¸ªäººåšå®¢
keyword: æ­åŸå°åˆ˜, iOS, VueJS, Flutter, React, React native, Swift, Python, Swift, Ruby, JS, Shell, å¤šç«¯èåˆèƒ½åŠ›, åŠ¨æ€åŒ–, å·¥ç¨‹åŒ–, è®¡ç®—æœºç½‘ç»œ, ç®—æ³•, æ“ä½œç³»ç»Ÿ, æ­å·, å·¥ç¨‹å¸ˆ, å¸ƒå¶çŒ«, è‹±çŸ­è“çŒ«, ç¨‹åºå‘˜
favicon: source/css/images/favicon.ico

excerpt_link: Read more

menu:
 ä¸»é¡µ: /
 æ ‡ç­¾: /tags/
 å½’æ¡£: /archives/
 é¡¹ç›®: /project/
 å…³äº: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

# comment: gitment

# gitment config
gitment:
  # enable: true
  # mint: true
  # count: true
  # lazy: false
  # githubID: FantasticLBP
  # repo: BlogComment
  # client_id: fb2253e8c91da9ff1efd
  # client_secret: aa4bdc8cc416db70bf06ce282d48cd58fc04dcfd

about: 
  banner: http://file.muyutech.com/about.jpg
  avatar: https://avatar-static.segmentfault.com/233/198/2331980259-5d7d132970ed9_huge256
  description: '<p class="description"><p style="text-align:left; margin:100px 120px 20px 120px; font-size:17px; line-height:33px;">æˆ‘æ˜¯ LBPï¼Œæ¯•ä¸šäºæ­å·å¸ˆèŒƒå¤§å­¦ï¼Œè½¯ä»¶å·¥ç¨‹ä¸“ä¸š</p>
<p style="text-align:left; margin:0px 120px 20px 120px; font-size:17px; line-height:33px;">ç°åœ¨æ˜¯ä¸€å iOS èµ„æ·±å·¥ç¨‹å¸ˆã€‚ä¸“æ³¨äºå¤§å‰ç«¯é¢†åŸŸï¼Œå¤§å‰ç«¯æ¨¡å¼ä¸‹çš„æŠ€æœ¯éƒ½æ„Ÿå…´è¶£ï¼Œå¤šç«¯èåˆèƒ½åŠ›ã€åŠ¨æ€åŒ–ã€å·¥ç¨‹åŒ–éƒ½æ˜¯ç ”ç©¶çš„å†…å®¹ã€‚ä¸»è¦è¯­è¨€ Objective-Cã€Javascriptã€htmlã€Rubyã€Shellã€Nodejsã€PHPã€‚åšæŒ Markdown å†™ä½œ</p>
<p style="text-align:left; margin:0 120px 20px 120px; font-size:17px; line-height:33px;">å–œæ¬¢æ¢ç´¢å’Œç ”ç©¶æœªçŸ¥é¢†åŸŸå’Œäº‹ç‰©åŸç†ï¼Œæœ€è¿‘åœ¨å­¦ä¹ é‡‘èçŸ¥è¯†ã€‚ä¸æ–­å­¦ä¹ è¿›é˜¶ä¸­...</p>
<p style="text-align:left; margin:0 120px 20px 120px; font-size:17px; line-height:33px;">å–œæ¬¢ç¾é£Ÿã€ç”µå½±ã€ä¹’ä¹“çƒã€å±±åœ°è½¦ã€å® ç‰©ï¼Œå…»äº† ğŸ± è‹±çŸ­è“çŒ«å’Œå¸ƒå¶çŒ« ï¼Œåœ¨æ­å·çš„å¯ä»¥å’Œæˆ‘çº¦ ğŸ“ï¸ æˆ–è€…çˆ¬å±±æˆ–è€…çº¿ä¸‹èŠæŠ€æœ¯ ğŸ’»</p>
<p style="text-align:left; margin:0 120px 20px 120px; font-size:17px; line-height:33px;">Stay hungry, stay foolish. &&  Just have a little faith.</p>
</p>'
  weibo_username: 3194053975
  email_username: wsbglbp@outlook.com
  github_username: FantasticLBP
  juejin_username: 57c108b8a633bd005d67e4a6
  segmentfault_username: fantasticbaby
  linkedin_username: æ–Œé¹-åˆ˜-8a9a04142

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
